name: dotnet pack and publish

on:
  release:
    types: [released]
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.403
      - name: Test
        run: dotnet test --verbosity normal
      - name: Build and pack
        run: VERSION=${GITHUB_REF##*/} dotnet build -warnaserror --no-restore -o . -c Release
      - name: Publish nuget package
        run: dotnet nuget push FSharp.Text.Docker.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
